// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCziZ_rP2vkvIhcrNiHg0DZBw4sKchlM2w',
    appId: '1:258537332920:web:f8ba17e34d4c51bc4e544d',
    messagingSenderId: '258537332920',
    projectId: 'social-midea-clone',
    authDomain: 'social-midea-clone.firebaseapp.com',
    storageBucket: 'social-midea-clone.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDLTizINWrAl6og_XjQnRu8UyZNIeKde7s',
    appId: '1:258537332920:android:a534cb6107c8c92b4e544d',
    messagingSenderId: '258537332920',
    projectId: 'social-midea-clone',
    storageBucket: 'social-midea-clone.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnciy6FLC2Eieoq_RVWYY8jqxK-0NAndg',
    appId: '1:258537332920:ios:c9ddc91ce155a7844e544d',
    messagingSenderId: '258537332920',
    projectId: 'social-midea-clone',
    storageBucket: 'social-midea-clone.appspot.com',
    iosBundleId: 'com.example.socialMediaClone',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnciy6FLC2Eieoq_RVWYY8jqxK-0NAndg',
    appId: '1:258537332920:ios:a14006ef70de93a14e544d',
    messagingSenderId: '258537332920',
    projectId: 'social-midea-clone',
    storageBucket: 'social-midea-clone.appspot.com',
    iosBundleId: 'com.example.socialMediaClone.RunnerTests',
  );
}
